import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "te" | "hi";

export const translations = {
  en: {
    // Nav
    dashboard: "Dashboard",
    recordVitals: "Record Vitals",
    history: "History",
    analytics: "Analytics",
    aiInsights: "AI Insights",
    aiAssistant: "AI Assistant",
    alerts: "Alerts",
    appointments: "Appointments",
    hospitals: "Hospitals",
    ambulance: "Ambulance",
    bloodDonation: "Blood Donation",
    govtSchemes: "Govt Schemes",
    settings: "Settings",
    signOut: "Sign out",
    patients: "Patients",
    doctors: "Doctors",
    bedManagement: "Bed Management",
    language: "Language",
    // Dashboard
    welcomeBack: "Welcome back",
    healthSummary: "Here is your health summary for today.",
    overallStatus: "Overall Status",
    heartRate: "Heart Rate",
    bloodPressure: "Blood Pressure",
    temperature: "Temperature",
    recentActivity: "Recent Activity",
    recentAlerts: "Recent Alerts",
    latestVitals: "Your latest recorded vitals",
    notificationsAttention: "Notifications requiring attention",
    noRecentVitals: "No recent vitals found.",
    noRecentAlerts: "No recent alerts.",
    emergency: "Emergency",
    // Vitals Form
    recordVitalsTitle: "Record Vitals",
    enterMeasurements: "Enter your current health measurements.",
    healthMeasurements: "Health Measurements",
    allFieldsRequired: "All fields except notes are required.",
    heartRateBpm: "Heart Rate (bpm)",
    bloodPressureMmhg: "Blood Pressure (mmHg)",
    bloodOxygen: "Blood Oxygen, SpO2 (%)",
    bodyTemperature: "Body Temperature (°C)",
    bloodGlucose: "Blood Glucose (mg/dL)",
    additionalNotes: "Additional Notes",
    howAreYouFeeling: "How are you feeling today?",
    saveRecord: "Save Record",
    cancel: "Cancel",
    vitalsSuccess: "Vitals recorded successfully",
    vitalsFail: "Failed to record vitals",
    // History
    vitalsHistory: "Vitals History",
    chronologicalTimeline: "A chronological timeline of your health measurements.",
    totalRecords: "Total Records",
    totalAlerts: "Total Alerts",
    criticalReadings: "Critical Readings",
    timeline: "Timeline",
    yourMeasurements: "Your measurements over time",
    noRecords: "No records found.",
    // Alerts
    alertsNotifications: "Alerts & Notifications",
    healthWarnings: "Important health warnings and system notifications.",
    markRead: "Mark Read",
    allCaughtUp: "All caught up",
    noActiveAlerts: "You have no active alerts.",
    // Appointments
    nearbyDoctors: "Nearby Doctors",
    topRatedSpecialists: "Top-rated specialists available near you — book instantly.",
    availableNow: "Available Now",
    bookAppointment: "Book Appointment",
    myAppointments: "My Appointments",
    manageAppointments: "Manage your upcoming and past doctor visits.",
    reschedule: "Reschedule",
    noAppointments: "No appointments found",
    noUpcoming: "You have no upcoming or past appointments.",
    experience: "Experience",
    rating: "Rating",
    fee: "Fee",
    appointmentConfirmed: "Appointment Confirmed!",
    confirmBooking: "Confirm Booking",
    unavailable: "Unavailable",
    // Hospitals
    findBestHospitals: "Find the Best Hospitals",
    accessPremiumCare: "Access premium healthcare facilities near you. Real-time bed availability, ICU status, and instant appointment booking.",
    searchHospitals: "Search hospitals, locations...",
    allSpecialties: "All Specialties",
    availableBeds: "Total Available Beds",
    icuBeds: "ICU Beds Available",
    partnerHospitals: "Partner Hospitals",
    topRated: "Top Rated",
    allHospitals: "All Hospitals",
    noHospitals: "No hospitals found",
    adjustFilters: "Try adjusting your search or filters.",
    call: "Call",
    specialties: "Specialties",
    // AI Assistant
    aiHealthAssistant: "AI Health Assistant",
    askAnything: "Ask anything — powered by medical AI. Voice-enabled.",
    online: "Online",
    getReport: "Get Report",
    generating: "Generating...",
    downloadReport: "Download PDF Report",
    thinking: "Thinking...",
    listeningSpeak: "Listening... speak now",
    askHealth: "Ask anything about your health...",
    alwaysConsult: "AI can make mistakes. Always consult a real doctor for medical advice.",
    voiceError: "Voice error",
    couldNotCapture: "Could not capture voice. Please try again.",
    reportDownloaded: "Report downloaded",
    reportSuccess: "Your health report has been downloaded successfully.",
    reportFailed: "Report failed",
    // AI Insights
    aiInsightsTitle: "AI Health Insights",
    poweredByAI: "Personalized health analysis powered by AI",
    healthScore: "Health Score",
    overallHealth: "Overall Health",
    basedOn: "Based on",
    readings: "readings",
    noInsights: "No insights available yet.",
    recordVitalsFirst: "Record some vitals first to get AI-powered health insights.",
    // General
    loading: "Loading...",
    search: "Search",
    filter: "Filter",
    status: "Status",
    date: "Date",
    time: "Time",
    notes: "Notes",
    normal: "Normal",
    risk: "Risk",
    critical: "Critical",
    warning: "Warning",
    close: "Close",
    save: "Save",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    skip: "Skip",
  },

  te: {
    // Nav
    dashboard: "డాష్‌బోర్డ్",
    recordVitals: "వైటల్స్ నమోదు",
    history: "చరిత్ర",
    analytics: "విశ్లేషణలు",
    aiInsights: "AI అంతర్దృష్టులు",
    aiAssistant: "AI సహాయకుడు",
    alerts: "హెచ్చరికలు",
    appointments: "అపాయింట్‌మెంట్లు",
    hospitals: "ఆసుపత్రులు",
    ambulance: "అంబులెన్స్",
    bloodDonation: "రక్తదానం",
    govtSchemes: "ప్రభుత్వ పథకాలు",
    settings: "సెట్టింగులు",
    signOut: "సైన్ అవుట్",
    patients: "రోగులు",
    doctors: "వైద్యులు",
    bedManagement: "బెడ్ నిర్వహణ",
    language: "భాష",
    // Dashboard
    welcomeBack: "స్వాగతం",
    healthSummary: "ఈరోజు మీ ఆరోగ్య సారాంశం ఇక్కడ ఉంది.",
    overallStatus: "మొత్తం స్థితి",
    heartRate: "హృదయ స్పందన రేటు",
    bloodPressure: "రక్తపోటు",
    temperature: "శరీర ఉష్ణోగ్రత",
    recentActivity: "ఇటీవలి కార్యకలాపాలు",
    recentAlerts: "ఇటీవలి హెచ్చరికలు",
    latestVitals: "మీరు ఇటీవల నమోదు చేసిన వైటల్స్",
    notificationsAttention: "శ్రద్ధ అవసరమయ్యే నోటిఫికేషన్లు",
    noRecentVitals: "ఇటీవలి వైటల్స్ కనుగొనబడలేదు.",
    noRecentAlerts: "ఇటీవలి హెచ్చరికలు లేవు.",
    emergency: "అత్యవసర",
    // Vitals Form
    recordVitalsTitle: "వైటల్స్ నమోదు చేయండి",
    enterMeasurements: "మీ ప్రస్తుత ఆరోగ్య కొలతలను నమోదు చేయండి.",
    healthMeasurements: "ఆరోగ్య కొలతలు",
    allFieldsRequired: "నోట్స్ తప్ప అన్ని ఫీల్డ్స్ తప్పనిసరి.",
    heartRateBpm: "హృదయ స్పందన రేటు (bpm)",
    bloodPressureMmhg: "రక్తపోటు (mmHg)",
    bloodOxygen: "రక్త ఆక్సిజన్, SpO2 (%)",
    bodyTemperature: "శరీర ఉష్ణోగ్రత (°C)",
    bloodGlucose: "రక్త గ్లూకోజ్ (mg/dL)",
    additionalNotes: "అదనపు గమనికలు",
    howAreYouFeeling: "ఈరోజు మీకు ఎలా అనిపిస్తుంది?",
    saveRecord: "రికార్డు సేవ్ చేయండి",
    cancel: "రద్దు చేయండి",
    vitalsSuccess: "వైటల్స్ విజయవంతంగా నమోదు చేయబడ్డాయి",
    vitalsFail: "వైటల్స్ నమోదు విఫలమైంది",
    // History
    vitalsHistory: "వైటల్స్ చరిత్ర",
    chronologicalTimeline: "మీ ఆరోగ్య కొలతల కాలానుక్రమ టైమ్‌లైన్.",
    totalRecords: "మొత్తం రికార్డులు",
    totalAlerts: "మొత్తం హెచ్చరికలు",
    criticalReadings: "క్రిటికల్ రీడింగులు",
    timeline: "టైమ్‌లైన్",
    yourMeasurements: "కాలంతో మీ కొలతలు",
    noRecords: "రికార్డులు కనుగొనబడలేదు.",
    // Alerts
    alertsNotifications: "హెచ్చరికలు & నోటిఫికేషన్లు",
    healthWarnings: "ముఖ్యమైన ఆరోగ్య హెచ్చరికలు మరియు సిస్టమ్ నోటిఫికేషన్లు.",
    markRead: "చదివినట్టు గుర్తించండి",
    allCaughtUp: "అన్నీ పూర్తయ్యాయి",
    noActiveAlerts: "మీకు యాక్టివ్ హెచ్చరికలు లేవు.",
    // Appointments
    nearbyDoctors: "సమీప వైద్యులు",
    topRatedSpecialists: "మీ దగ్గర అందుబాటులో ఉన్న అత్యుత్తమ నిపుణులు — వెంటనే బుక్ చేయండి.",
    availableNow: "ఇప్పుడు అందుబాటులో ఉన్నారు",
    bookAppointment: "అపాయింట్‌మెంట్ బుక్ చేయండి",
    myAppointments: "నా అపాయింట్‌మెంట్లు",
    manageAppointments: "మీ రాబోయే మరియు గత డాక్టర్ సందర్శనలను నిర్వహించండి.",
    reschedule: "తేదీ మార్చండి",
    noAppointments: "అపాయింట్‌మెంట్లు కనుగొనబడలేదు",
    noUpcoming: "మీకు రాబోయే లేదా గత అపాయింట్‌మెంట్లు లేవు.",
    experience: "అనుభవం",
    rating: "రేటింగ్",
    fee: "రుసుము",
    appointmentConfirmed: "అపాయింట్‌మెంట్ నిర్ధారించబడింది!",
    confirmBooking: "బుకింగ్ నిర్ధారించండి",
    unavailable: "అందుబాటులో లేదు",
    // Hospitals
    findBestHospitals: "అత్యుత్తమ ఆసుపత్రులను కనుగొనండి",
    accessPremiumCare: "మీ దగ్గర ప్రీమియం హెల్త్‌కేర్ సౌకర్యాలను యాక్సెస్ చేయండి.",
    searchHospitals: "ఆసుపత్రులు, స్థానాలను వెతకండి...",
    allSpecialties: "అన్ని స్పెషాలిటీలు",
    availableBeds: "మొత్తం అందుబాటు బెడ్స్",
    icuBeds: "ICU బెడ్స్ అందుబాటు",
    partnerHospitals: "భాగస్వామ్య ఆసుపత్రులు",
    topRated: "అత్యధిక రేటింగ్",
    allHospitals: "అన్ని ఆసుపత్రులు",
    noHospitals: "ఆసుపత్రులు కనుగొనబడలేదు",
    adjustFilters: "మీ శోధన లేదా ఫిల్టర్‌లను సర్దుబాటు చేయండి.",
    call: "కాల్ చేయండి",
    specialties: "స్పెషాలిటీలు",
    // AI Assistant
    aiHealthAssistant: "AI ఆరోగ్య సహాయకుడు",
    askAnything: "ఏదైనా అడగండి — మెడికల్ AI ద్వారా. వాయిస్ ఎనేబుల్డ్.",
    online: "ఆన్‌లైన్",
    getReport: "నివేదిక పొందండి",
    generating: "తయారవుతోంది...",
    downloadReport: "PDF నివేదిక డౌన్‌లోడ్ చేయండి",
    thinking: "ఆలోచిస్తోంది...",
    listeningSpeak: "వింటోంది... మాట్లాడండి",
    askHealth: "మీ ఆరోగ్యం గురించి ఏదైనా అడగండి...",
    alwaysConsult: "AI తప్పులు చేయవచ్చు. వైద్య సలహా కోసం ఎప్పుడూ నిజమైన డాక్టర్‌ని సంప్రదించండి.",
    voiceError: "వాయిస్ లోపం",
    couldNotCapture: "వాయిస్ క్యాప్చర్ చేయలేకపోయింది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
    reportDownloaded: "నివేదిక డౌన్‌లోడ్ అయింది",
    reportSuccess: "మీ ఆరోగ్య నివేదిక విజయవంతంగా డౌన్‌లోడ్ అయింది.",
    reportFailed: "నివేదిక విఫలమైంది",
    // AI Insights
    aiInsightsTitle: "AI ఆరోగ్య అంతర్దృష్టులు",
    poweredByAI: "AI ద్వారా వ్యక్తిగత ఆరోగ్య విశ్లేషణ",
    healthScore: "ఆరోగ్య స్కోరు",
    overallHealth: "మొత్తం ఆరోగ్యం",
    basedOn: "ఆధారంగా",
    readings: "రీడింగులు",
    noInsights: "ఇంకా అంతర్దృష్టులు అందుబాటులో లేవు.",
    recordVitalsFirst: "AI ఆరోగ్య అంతర్దృష్టులు పొందడానికి ముందు కొన్ని వైటల్స్ నమోదు చేయండి.",
    // General
    loading: "లోడవుతోంది...",
    search: "వెతకండి",
    filter: "ఫిల్టర్",
    status: "స్థితి",
    date: "తేదీ",
    time: "సమయం",
    notes: "గమనికలు",
    normal: "సాధారణ",
    risk: "ప్రమాదం",
    critical: "క్రిటికల్",
    warning: "హెచ్చరిక",
    close: "మూసివేయండి",
    save: "సేవ్ చేయండి",
    confirm: "నిర్ధారించండి",
    back: "వెనక్కి",
    next: "తదుపరి",
    skip: "దాటవేయండి",
  },

  hi: {
    // Nav
    dashboard: "डैशबोर्ड",
    recordVitals: "वाइटल्स दर्ज करें",
    history: "इतिहास",
    analytics: "विश्लेषण",
    aiInsights: "AI अंतर्दृष्टि",
    aiAssistant: "AI सहायक",
    alerts: "अलर्ट",
    appointments: "अपॉइंटमेंट",
    hospitals: "अस्पताल",
    ambulance: "एम्बुलेंस",
    bloodDonation: "रक्तदान",
    govtSchemes: "सरकारी योजनाएं",
    settings: "सेटिंग्स",
    signOut: "साइन आउट",
    patients: "मरीज़",
    doctors: "डॉक्टर",
    bedManagement: "बेड प्रबंधन",
    language: "भाषा",
    // Dashboard
    welcomeBack: "वापसी पर स्वागत है",
    healthSummary: "आज का आपका स्वास्थ्य सारांश यहां है।",
    overallStatus: "समग्र स्थिति",
    heartRate: "हृदय गति",
    bloodPressure: "रक्तचाप",
    temperature: "तापमान",
    recentActivity: "हाल की गतिविधि",
    recentAlerts: "हाल के अलर्ट",
    latestVitals: "आपके हाल ही में दर्ज किए गए वाइटल्स",
    notificationsAttention: "ध्यान देने योग्य सूचनाएं",
    noRecentVitals: "हाल के वाइटल्स नहीं मिले।",
    noRecentAlerts: "हाल के अलर्ट नहीं हैं।",
    emergency: "आपातकाल",
    // Vitals Form
    recordVitalsTitle: "वाइटल्स दर्ज करें",
    enterMeasurements: "अपने वर्तमान स्वास्थ्य मापों को दर्ज करें।",
    healthMeasurements: "स्वास्थ्य माप",
    allFieldsRequired: "नोट्स को छोड़कर सभी फ़ील्ड आवश्यक हैं।",
    heartRateBpm: "हृदय गति (bpm)",
    bloodPressureMmhg: "रक्तचाप (mmHg)",
    bloodOxygen: "रक्त ऑक्सीजन, SpO2 (%)",
    bodyTemperature: "शरीर का तापमान (°C)",
    bloodGlucose: "रक्त शर्करा (mg/dL)",
    additionalNotes: "अतिरिक्त नोट्स",
    howAreYouFeeling: "आज आप कैसा महसूस कर रहे हैं?",
    saveRecord: "रिकॉर्ड सहेजें",
    cancel: "रद्द करें",
    vitalsSuccess: "वाइटल्स सफलतापूर्वक दर्ज किए गए",
    vitalsFail: "वाइटल्स दर्ज करने में विफल",
    // History
    vitalsHistory: "वाइटल्स इतिहास",
    chronologicalTimeline: "आपके स्वास्थ्य मापों की कालानुक्रमिक समयरेखा।",
    totalRecords: "कुल रिकॉर्ड",
    totalAlerts: "कुल अलर्ट",
    criticalReadings: "गंभीर रीडिंग",
    timeline: "समयरेखा",
    yourMeasurements: "समय के साथ आपके माप",
    noRecords: "कोई रिकॉर्ड नहीं मिला।",
    // Alerts
    alertsNotifications: "अलर्ट और सूचनाएं",
    healthWarnings: "महत्वपूर्ण स्वास्थ्य चेतावनियां और सिस्टम सूचनाएं।",
    markRead: "पढ़ा हुआ चिह्नित करें",
    allCaughtUp: "सब कुछ ठीक है",
    noActiveAlerts: "आपके पास कोई सक्रिय अलर्ट नहीं है।",
    // Appointments
    nearbyDoctors: "पास के डॉक्टर",
    topRatedSpecialists: "आपके पास उपलब्ध शीर्ष-रेटेड विशेषज्ञ — तुरंत बुक करें।",
    availableNow: "अभी उपलब्ध",
    bookAppointment: "अपॉइंटमेंट बुक करें",
    myAppointments: "मेरे अपॉइंटमेंट",
    manageAppointments: "अपनी आगामी और पिछली डॉक्टर विजिट प्रबंधित करें।",
    reschedule: "पुनर्निर्धारित करें",
    noAppointments: "कोई अपॉइंटमेंट नहीं मिला",
    noUpcoming: "आपके पास कोई आगामी या पिछला अपॉइंटमेंट नहीं है।",
    experience: "अनुभव",
    rating: "रेटिंग",
    fee: "शुल्क",
    appointmentConfirmed: "अपॉइंटमेंट की पुष्टि हो गई!",
    confirmBooking: "बुकिंग की पुष्टि करें",
    unavailable: "उपलब्ध नहीं",
    // Hospitals
    findBestHospitals: "सर्वश्रेष्ठ अस्पताल खोजें",
    accessPremiumCare: "अपने पास प्रीमियम स्वास्थ्य सेवा सुविधाएं एक्सेस करें।",
    searchHospitals: "अस्पताल, स्थान खोजें...",
    allSpecialties: "सभी विशेषताएं",
    availableBeds: "कुल उपलब्ध बेड",
    icuBeds: "ICU बेड उपलब्ध",
    partnerHospitals: "साझेदार अस्पताल",
    topRated: "शीर्ष रेटेड",
    allHospitals: "सभी अस्पताल",
    noHospitals: "कोई अस्पताल नहीं मिला",
    adjustFilters: "अपनी खोज या फ़िल्टर समायोजित करें।",
    call: "कॉल करें",
    specialties: "विशेषताएं",
    // AI Assistant
    aiHealthAssistant: "AI स्वास्थ्य सहायक",
    askAnything: "कुछ भी पूछें — मेडिकल AI द्वारा संचालित। वॉयस-सक्षम।",
    online: "ऑनलाइन",
    getReport: "रिपोर्ट प्राप्त करें",
    generating: "उत्पन्न हो रहा है...",
    downloadReport: "PDF रिपोर्ट डाउनलोड करें",
    thinking: "सोच रहा है...",
    listeningSpeak: "सुन रहा है... अभी बोलें",
    askHealth: "अपने स्वास्थ्य के बारे में कुछ भी पूछें...",
    alwaysConsult: "AI गलतियां कर सकता है। चिकित्सा सलाह के लिए हमेशा एक वास्तविक डॉक्टर से परामर्श करें।",
    voiceError: "वॉयस त्रुटि",
    couldNotCapture: "वॉयस कैप्चर नहीं कर सका। कृपया पुनः प्रयास करें।",
    reportDownloaded: "रिपोर्ट डाउनलोड हुई",
    reportSuccess: "आपकी स्वास्थ्य रिपोर्ट सफलतापूर्वक डाउनलोड हो गई।",
    reportFailed: "रिपोर्ट विफल",
    // AI Insights
    aiInsightsTitle: "AI स्वास्थ्य अंतर्दृष्टि",
    poweredByAI: "AI द्वारा संचालित व्यक्तिगत स्वास्थ्य विश्लेषण",
    healthScore: "स्वास्थ्य स्कोर",
    overallHealth: "समग्र स्वास्थ्य",
    basedOn: "के आधार पर",
    readings: "रीडिंग",
    noInsights: "अभी तक कोई अंतर्दृष्टि उपलब्ध नहीं।",
    recordVitalsFirst: "AI स्वास्थ्य अंतर्दृष्टि पाने के लिए पहले कुछ वाइटल्स दर्ज करें।",
    // General
    loading: "लोड हो रहा है...",
    search: "खोजें",
    filter: "फ़िल्टर",
    status: "स्थिति",
    date: "तारीख",
    time: "समय",
    notes: "नोट्स",
    normal: "सामान्य",
    risk: "जोखिम",
    critical: "गंभीर",
    warning: "चेतावनी",
    close: "बंद करें",
    save: "सहेजें",
    confirm: "पुष्टि करें",
    back: "वापस",
    next: "अगला",
    skip: "छोड़ें",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem("vitalcare_language") as Language) || "en";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("vitalcare_language", lang);
  };

  const t = (key: TranslationKey): string => {
    return translations[language][key] as string;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within a LanguageProvider");
  return ctx;
}
